# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8bd8efb2d6db7fb4494f914902a7adcd78d6694cfac80a3fc954d08fe2730be18c1a33ac1c821eaf8d1a95fedcf4023cff182992bc183e343d659f94d17ef9

test:
  secret_key_base: ee36e1f430092f879758c5f64dd8c43cd03bf4a8e9259557f8bf002deee8cd1dbb031176c70dbe4cfe2d2ffb9da9c9ad6483be7ce1b2d8b7e9fbf465b1901dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
